language: node_js
node_js:
  - lts/*
cache:
  directories:
    - "node_modules"
branches:
  except:
    - gh-pages
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master